checks:
  php:
    code_rating: true
    duplication: true

build:
  environment:
    php: "8.1"

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

  tests:
    before:
      - "phpunit"

before_commands:
  - "composer install --no-interaction --prefer-source"

filter:
  excluded_paths:
    - tests/